name = "cf-ais-worker"
compatibility_date = "2024-01-01"

main = "worker.js"

[vars]
OPENAI_API_KEYS ="sk-1,sk-2,sk-3,sk-4,sk-5,sk-6"
SUM_MODEL = "gpt-4.1-mini"
OPENAI_API_BASE = "https://api.openai.com/v1"